export const products = [
  {
    id: 1,
    name: "Color Vinyl Stickers",
    description: "Stika za vinyl zenye rangi mbalimbali",
    category: "vinyl",
    slug: "color-vinyl-stickers",
    imageUrl: null, // Will be populated from Cloudinary via admin
    variants: [], // Will store product variants from admin
  },
  {
    id: 2,
    name: "Wrapping Stickers",
    description: "Stika za kufunika magari au vifaa kwa mwonekano wa kisasa",
    category: "wrapping",
    slug: "wrapping-stickers",
    imageUrl: null,
    variants: [],
  },
  {
    id: 3,
    name: "Reflective Sheeting",
    description: "Soft and Hard Materials (kwa barabara, Mabango, Magari n.k.)",
    category: "reflective",
    slug: "reflective-sheeting",
    imageUrl: null,
    variants: [],
  },
  {
    id: 4,
    name: "EGP Reflective Sheeting",
    description: "Sheeting za EGP zenye mwanga mkali na uimara kwa alama za barabarani na matumizi ya usalama",
    category: "reflective",
    slug: "egp-reflective-sheeting",
    imageUrl: null,
    variants: [],
  },
  {
    id: 5,
    name: "Wood Stickers",
    description: "Stika zenye muonekano au muundo wa mbao",
    category: "decorative",
    slug: "wood-stickers",
    imageUrl: null,
    variants: [],
  },
  {
    id: 6,
    name: "Marble Sheets",
    description: "Stika au karatasi zenye muundo wa marumaru (marble finish)",
    category: "decorative",
    slug: "marble-sheets",
    imageUrl: null,
    variants: [],
  },
  {
    id: 7,
    name: "Headlight Stickers",
    description: "Stika za kufunika au kulinda taa za magari na pikipiki",
    category: "automotive",
    slug: "headlight-stickers",
    imageUrl: null,
    variants: [],
  },
  {
    id: 8,
    name: "3M Reflective Tapes",
    description: "Tepu maalumu zinazotumika katika magari kwa lengo la usalama",
    category: "reflective",
    slug: "3m-reflective-tapes",
    imageUrl: null,
    variants: [],
  },
  {
    id: 9,
    name: "Gold & Chrome Mirror",
    description: "Stika zenye mwonekano wa kioo",
    category: "decorative",
    slug: "gold-chrome-mirror",
    imageUrl: null,
    variants: [],
  },
  {
    id: 10,
    name: "Heat Transfer Stickers",
    description: "Stika za kuhamisha kwa joto (kwa T-shirt na nguo)",
    category: "transfer",
    slug: "heat-transfer-stickers",
    imageUrl: null,
    variants: [],
  },
  {
    id: 11,
    name: "Tinted Stickers",
    description: "Stika za tint (kivuli kwa madirisha na vioo)",
    category: "automotive",
    slug: "tinted-stickers",
    imageUrl: null,
    variants: [],
  },
  {
    id: 12,
    name: "Frost Stickers",
    description: "Stika za kutoa mwonekano wa ukungu/frost kwenye vioo",
    category: "decorative",
    slug: "frost-stickers",
    imageUrl: null,
    variants: [],
  },
  {
    id: 13,
    name: "Self-Adhesive Vinyl",
    description: "Vinyl yenye gundi tayari kwa matumizi mbalimbali ya Kuprint",
    category: "vinyl",
    slug: "self-adhesive-vinyl",
    imageUrl: null,
    variants: [],
  },
  {
    id: 14,
    name: "Events Stickers",
    description: "Stika maalum kwa hafla au matukio",
    category: "custom",
    slug: "events-stickers",
    imageUrl: null,
    variants: [],
  },
  {
    id: 15,
    name: "Sticker Tools",
    description: "Vifaa vya kubandikia au kufanya kazi na stika",
    category: "tools",
    slug: "sticker-tools",
    imageUrl: null,
    variants: [],
  },
]
